jsconfig.json

- jsconfig.json 수정
- root dir 로 이동

misc: Modify and Move jsconfig.json to root dir

---

api/index.js
api/package.json

* 아주아주아주아주 간단한 로그인 세션 저장을 만듭니다.
mysql - table에 세션을 저장하는 방법입니다.
🌱 일반적으로 실무에서는 table에 세션 데이터를 저장하지 않습니다!!
redis와 같은곳에 보통 저장합니다.

api: session 추가

---

app/src/Routes.js
app/src/socket/http-test.js

* http test를 위한 프론트 테스트 페이지 입니다.

app: http test 페이지 생성

---

api/db/schema/account.sql
api/db/schema/member.sql
api/db/schema/member_group.sql
api/db/schema/part.sql
api/db/schema/room.sql

api: db schema 추가

---

api/index.js
api/package.json
api/routes/auth/index.js
api/routes/index.js

api: remove session code

---

api/core/util/auth.js
api/package.json

accessToken 암호화/복호화를 위한 함수를 추가합니다.

api: accessToken 암호화/복호화를 위한 함수 추가

---

api/core/component/auth/index.js
api/core/component/group/index.js
api/core/util/auth.js
api/routes/auth/index.js
api/routes/group/index.js
api/routes/index.js
app/src/socket/http-test.js

api, groups (부서정보), groupMembers (부서별 임직원 목록), auth (로그인)

api: auth, groups, groupMembers api 추가

---

api/core/component/desk/index.js
api/core/component/part/index.js
api/routes/desk/index.js
api/routes/index.js
api/routes/part/index.js
app/src/socket/http-test.js

part (부품들 - 책상을 제외한 모든.. 창문, 문, 길, 프린터기 등등등)
desk (책상)
목록 조회 api 추가

api: part, desk dummy api 추가

---

api/core/component/group/index.js

api: 부서정보 받아갈 때 색상 추가

---

api/core/component/auth/index.js
api/routes/auth/index.js
app/src/pages/Login.jsx

sign-in api, view 구현
view에는 기능만 붙여두었습니다. 동작 참고를 위하여..

api: sign-in api, view 구현

---

app/src/api/http-client.js
app/src/pages/Login.jsx

* login page에 axios 의존성 제거
* 서버 url 수정

app: login httpClient 적용

---

app/src/components/grid/Grid.jsx

GridItem의 x, y값을 반대로 설정해놓은 부분 수정하였습니다..😂

app: x, y값 수정

---

app/src/components/grid/Grid.jsx

* drag&drop으로 놓으려고하는 자리에 무엇인가가 있다면 서로 자리를 바꿈
* 무엇인가가 있었던 자리에는 다시 drop 수 없는 오류 수정 ({} => delete)

app: 놓으려는 자리에 뭔가가 있다면 서로 바꾸기

---

app/src/components/grid/Grid.jsx
app/src/components/grid/GridItem.js

fix: Fix proptype.

---

api/routes/room/index.js

api: remove room endpoint 추가

---

api/core/service/group/index.js

api: group/members api 구조가 바뀐 오류 수정

---

app/src/components/Button.jsx
app/src/components/Input.jsx
app/src/pages/Login.jsx
app/src/pages/Main.jsx

Main 페이지 최초 랜더될 때 accessToken 여부를 체크합니다.

app: accessToken 여부에 따른 router 경로 추가

---

app/src/components/grid/Grid.jsx
app/src/components/grid/GridItem.js

- 그리드 내 클릭 시 아이템 추가, 삭제
- addNewItem 으로 분리

Feature: 그리드 내 클릭 시 아이템 추가, 삭제

---

app/src/components/InfoModal.jsx
app/src/pages/Main.jsx

- '방추가' 버튼 클릭하여 방 만들기 기능
- 확인 > info 모달 노출

Feature: '방추가' 버튼 클릭하여 방 만들기 기능

---

app/src/components/grid/Grid.jsx

- 함수 define 전에 사용되어 발생한 lint 에러 해결

fix: Fix lint error.

---

app/src/components/grid/Grid.jsx

feature: Grid 정렬 변수로 수정

---

app/src/pages/Login.jsx

- 로그인 페이지 진입 시 accessToken을 체크
- input에서 엔터키 입력 시 submit

feature: accessToken 여부에 따라 로그인 페이지 경로 수정

---

app/src/components/grid/GridItem.js

- GridItem의 type에 따라 색상을 변경합니다.

feature: type에 따른 GridItem 배경색 변경

---

api/core/repository/accountRepository.js
api/core/service/auth/index.js
api/core/support/db-connection.js
api/core/util/auth.js
api/routes/auth/index.js
app/src/pages/Login.jsx

api: signIn db 연동

---

app/src/common/api/auth.js
app/src/common/api/grid.js
app/src/common/api/group.js
app/src/common/api/room.js
app/src/common/api/socket.js
app/src/common/support/http-client.js
app/src/components/grid/Grid.jsx
app/src/pages/Login.jsx
app/src/pages/Main.jsx

- form 태그 에러를 수정하며 컴파일 에러를 수정했습니다!

app: export default lint 에러 및 form 에러 수정

---

app/src/components/grid/Grid.jsx

* 동시편집을 지원합니다.
삭제에 대한 이벤트는 추가하지 않았습니다.
로컬에서 브라우저 2개를 열어서 테스트 가능합니다.

app: 여러 사용자들이 동시편집 기능을 적용

---

app/src/common/policy/index.js
app/src/pages/Login.jsx

* accessToken은 api통신을 할 때 필요합니다.

app: 로그인 후 accessToken을 socket에 저장

---

app/src/components/_styled/CommonIconBox.jsx
app/src/components/grid/Grid.jsx
app/src/components/grid/GridItem.js
app/src/components/icons/DeleteIcon.jsx
app/src/components/sidebar/GroupHeader.jsx
app/src/components/sidebar/Sidebar.jsx
app/src/store/Store.js

그리드 내 새로운 곳 클릭 시 새로운 아이템 추가, 
존재하는 아이템 클릭시 삭제버튼 표시

feature: 그리드 내 새로운 곳 클릭 시 새로운 아이템 추가, 존재하는 아이템 클릭시 삭제버튼 표시

---

app/src/common/api/room.js
app/src/components/Tabs.jsx
app/src/pages/Main.jsx

* room 삭제 기능 추가
기능구현에 의의를 둡니다..

app: room delete 추가

---

api/core/repository/Repository.js
api/core/repository/memberRepository.js
api/core/repository/partRepository.js

* 데이터를 실제 삭제하면 문제가 있음
* state만 DELETE로 수정하고
* 모든 조회에서 state = NORMAL 조건 추가

api: delete를 실행하면 state만 deleted로 수정

---

api/core/repository/partRepository.js
api/core/service/part/index.js
api/core/socketio/append-location.js
app/src/components/grid/Grid.jsx

app: 사람 배치는 빈자리에만 올릴 수 있음

---

app/src/components/grid/GridItem.js
app/src/components/sidebar/GroupHeader.jsx
app/src/components/sidebar/Sidebar.jsx
app/src/index.js
app/src/styles/theme.js

- GridItem 사이즈 및 Sidebar 등의 레이아웃이 수정되었습니다.

feature: 공통 색상 theme.js에 추가 및 활용, 기타 스타일 수정

---

app/src/common/policy/index.js
app/src/components/grid/Grid.jsx
app/src/components/grid/GridItem.js
app/src/components/sidebar/Sidebar.jsx
app/src/styles/theme.js

* partList를 policy로 이동
* 색상값을 policy에서 지정하도록 수정

app: sideBar에 노출되는 partList를 policy로 이동

---

app/src/components/sidebar/GroupHeader.jsx
app/src/store/Store.js

sidebar 열리지 않는 이슈 해결, 그룹별로 열리게 수정

fix: sidebar 열리지 않는 이슈 해결, 그룹별로 열리게 수정

---

app/src/components/tab/TabItem.js
app/src/components/tab/Tabs.jsx
app/src/styles/GlobalStyle.js

- 명조체로.. 나오던 폰트 스타일 Noto sans로 수정합니다.
- tab 에 key (id)추가
- tab 폰트사이즈 조금 작게 수정

Redesign: 폰트 스타일 수정, tab 에 key 추가, tab 폰트사이즈 수정

---

app/src/components/grid/Grid.jsx
app/src/components/sidebar/Sidebar.jsx
app/src/components/tab/Tabs.jsx
app/src/pages/Main.jsx

- 레이아웃 및 사이즈를 수정하여 Grid 스크롤이 가능하도록 수정하였습니다.

feature: 레이아웃 수정

---

api/core/service/auth/index.js
api/routes/auth/index.js
app/src/common/policy/index.js
app/src/components/grid/Grid.jsx
app/src/components/grid/GridItem.js
app/src/components/tab/TabItem.js
app/src/components/tab/Tabs.jsx
app/src/pages/Login.jsx
app/src/pages/Main.jsx

* 우선 제출을 위해 요구사항 중 권한분리를 2개로만 합니다.
All or Nothing
계정: test / test => 권한 없음 => sideBar 안보임, 드래그 불가, 탭(room)편집 불가
계정: master / test => 권한 있음 => 모든 권한 가짐
> 권한이 없는 test / test 로그인 시 화면

api: 로그인 계정 권한에 따라 편집을 불가능하도록 합니다.

---

app/src/common/policy/index.js
app/src/components/grid/GridItem.js

policy: 요구사항에 맞춰 더 많은 part를 생성

---

app/src/components/grid/Grid.jsx
app/src/components/grid/GridItem.js
app/src/components/sidebar/Sidebar.jsx
app/src/store/Store.js

delete 아이콘 다른곳 클릭시, 탭 이동 시 사라지지 않는 이슈

fix: delete 아이콘 다른곳 클릭시, 탭 이동 시 사라지지 않는 이슈

---

app/src/components/grid/Grid.jsx
app/src/components/modal/InfoModal.jsx
app/src/pages/Main.jsx

feature: alert 를 info modal 로 대체

---

app/src/common/policy/index.js
app/src/components/sidebar/Sidebar.jsx

Redesign: styling

---

app/src/pages/Main.jsx

fix: 방 생성 시 infomodal 비어있는 메세지 노출되는 이슈 수정

---

app/src/components/sidebar/Sidebar.jsx

- Sidebar에 scroll-y: auto; 를 추가합니다.

feature: 스크롤 수정

---

app/src/components/sidebar/Sidebar.jsx

feature: dropdown 잘리는 버그 해결

---

app/src/components/grid/GridItem.js

fix: grid item 의 addNewItem 삭제 

---

app/src/common/policy/index.js
app/src/components/grid/Grid.jsx
app/src/components/grid/GridItem.js
app/src/components/sidebar/Sidebar.jsx
app/src/pages/Main.jsx

fix: member 색상 이슈, policy 사물 변경

---

app/src/common/policy/index.js
app/src/components/sidebar/Sidebar.jsx

fix: Sidebar unique key 에러 해결

---

app/src/components/sidebar/Sidebar.jsx
app/src/store/Store.js

- group 이 여러개 있을때 버튼식으로 추가되게 구현
- 쭉 리스트로 펼쳐지기에는 뎁스가 너무 있는것같아서 버튼식으로 구현했습니다.

feature: group이 여러개 있을때 버튼식으로 추가되게 구현 

---

app/src/styles/theme.js

redesign: member 디폴트 컬러 변경

---

app/src/common/policy/index.js
app/src/components/grid/Grid.jsx
app/src/components/grid/GridItem.js
app/src/components/sidebar/Sidebar.jsx
app/src/components/tab/TabItem.js
app/src/components/tab/Tabs.jsx
app/src/styles/theme.js

- sidebar 호버 효과
- type MEMBER 인 그리드 font bold 처리
- 기타 색상 수정

redesign:  배경, 보더 색 등 수정, hover 효과 적용 

---

.gitignore
Dockerfile
README.md
api/config/db.js
api/ecosystem.config.js
app/package-lock.json
app/package.json
app/public/index.html
app/src/common/api/socket.js
app/src/common/policy/index.js
app/src/components/grid/Grid.jsx
app/src/components/grid/GridItem.jsx
app/webpack.config.js
docker-compose.yml
docker/mysql/db_schema.sql

* 프론트에서 socker.io dependency 제거
* docker-compuse 를 위한 yml 파일을 구성
사용법 :
```
docker image build -t placer .
docer-compuse-up
```

docker compuse yml 구성
